version: 2.1

jobs:
  rubyVersion1:
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run: export BUNDLE_GEMFILE=$PWD/Gemfile
      - run: ruby --version
      - run: gem update --system
      - run: gem install bundler -v '< 2'
      - run: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
      - run: bundle exec rake

  rubyVersion2:
    docker:
      - image: circleci/ruby:2.6.0
    steps:
      - checkout
      - run: export BUNDLE_GEMFILE=$PWD/Gemfile
      - run: ruby --version
      - run: gem update --system
      - run: gem install bundler -v '< 2'
      - run: bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
      - run: bundle exec rake

workflows:
  run-jobs:
    jobs:
      - rubyVersion1
      - rubyVersion2