version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604::202010-01

    steps:
      - checkout
      - run:
          command: |
            rvm use 2.6.0 --install --binary --fuzzy
            # rvm use 2.5.3 --install --binary --fuzzy
            export BUNDLE_GEMFILE=$PWD/Gemfile
            echo "Setting up build cache"
            echo "adding /home/travis/build/heroku/vault-tools/vendor/bundle to cache"
            ruby --version
            gem install bundler -v '< 2'
            bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
            bundle exec rake
