name: heroku/vault-tools/heroku/vault-tools
on:
  push:
jobs:
  build:
    runs-on: sfdc-hk-ubuntu-latest
    container:
      image: ruby:2.7.1
    steps:
    - uses: actions/checkout@v2
    - run: export BUNDLE_GEMFILE=$PWD/Gemfile
    - run: ruby --version
    - run: gem update --system
    - run: gem install bundler -v '< 2'
    - run: bundle install --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}
    - run: bundle exec rake
